baseurl = "http://nihildeb.github.io/hme/"
languageCode = "en-us"
title= "Happy Moose Engine"
theme = "crisp"
paginate = 10
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2015"
canonifyurls = true
layoutdir= "layouts"
publishdir= ".."
